import {test,expect} from '@playwright/test'
test("Test1@sanity",async({page})=>{
    console.log("Test1")
});
test("Test2@sanity",async({page})=>{
    console.log("Test2")
});
test("Test3@regression",async({page})=>{
    console.log("Test3")
});
test("Test4@regression",async({page})=>{
    console.log("Test4")
});
test("Test5@sanity@regression",async({page})=>{
    console.log("Test5")
});
test("Test6@sanity@regression",async({page})=>{
    console.log("Test6")
});
